import { RailwayStationInfo } from '../types';

export const MUMBAI_RAILWAY_STATIONS: Record<string, RailwayStationInfo[]> = {
  'gateway-of-india': [
    {
      id: 'churchgate',
      name: 'Churchgate Railway Station',
      code: 'CCG',
      line: 'Western Railway (Terminal)',
      distance_km: 2.3,
      walking_time_mins: 28,
      road_time_mins: 8,
      transfer_modes: ['Taxi', 'BEST Bus (138, 112)', 'Walk'],
    },
    {
      id: 'csmt',
      name: 'Chhatrapati Shivaji Maharaj Terminus (CSMT)',
      code: 'CSMT',
      line: 'Central & Harbour Line (Terminal)',
      distance_km: 2.8,
      walking_time_mins: 34,
      road_time_mins: 10,
      transfer_modes: ['Taxi', 'BEST Bus (111, 112)', 'Walk'],
    },
  ],
  'marine-drive': [
    {
      id: 'marine-lines',
      name: 'Marine Lines Station',
      code: 'MEL',
      line: 'Western Line',
      distance_km: 0.6,
      walking_time_mins: 8,
      road_time_mins: 3,
      transfer_modes: ['Walk', 'Taxi'],
    },
    {
      id: 'churchgate',
      name: 'Churchgate Station',
      code: 'CCG',
      line: 'Western Line',
      distance_km: 1.1,
      walking_time_mins: 14,
      road_time_mins: 4,
      transfer_modes: ['Walk', 'Taxi'],
    },
    {
      id: 'charni-road',
      name: 'Charni Road Station',
      code: 'CYR',
      line: 'Western Line (Near Girgaon Chowpatty)',
      distance_km: 1.4,
      walking_time_mins: 18,
      road_time_mins: 5,
      transfer_modes: ['Walk', 'Taxi'],
    },
  ],
  'csmt': [
    {
      id: 'csmt',
      name: 'CSMT Railway Station',
      code: 'CSMT',
      line: 'Central & Harbour Lines',
      distance_km: 0.1,
      walking_time_mins: 1,
      road_time_mins: 1,
      transfer_modes: ['Suburban Trains', 'Long Distance Express', 'Walk'],
    },
    {
      id: 'masjid',
      name: 'Masjid Bunder Station',
      code: 'MSD',
      line: 'Central & Harbour Lines',
      distance_km: 1.2,
      walking_time_mins: 15,
      road_time_mins: 5,
      transfer_modes: ['Taxi', 'Walk'],
    },
  ],
  'elephanta-caves': [
    {
      id: 'churchgate',
      name: 'Churchgate (via Gateway Ferry Wharf)',
      code: 'CCG',
      line: 'Western Line + 55m Ferry Transfer',
      distance_km: 12.0,
      walking_time_mins: 60,
      road_time_mins: 20,
      transfer_modes: ['Ferry Boat from Gateway Jetty No. 1', 'Taxi to Station'],
    },
    {
      id: 'csmt',
      name: 'CSMT (via Gateway Ferry Wharf)',
      code: 'CSMT',
      line: 'Central Line + 55m Ferry Transfer',
      distance_km: 12.5,
      walking_time_mins: 65,
      road_time_mins: 22,
      transfer_modes: ['Ferry Boat from Gateway Jetty No. 1', 'Taxi to Station'],
    },
  ],
  'kanheri-caves': [
    {
      id: 'borivali',
      name: 'Borivali Railway Station',
      code: 'BVI',
      line: 'Western Railway (Fast Train Hub)',
      distance_km: 6.8,
      walking_time_mins: 85,
      road_time_mins: 22,
      transfer_modes: ['BEST Safari Bus', 'Auto Rickshaw', 'Taxi'],
    },
  ],
  'sanjay-gandhi-national-park': [
    {
      id: 'borivali',
      name: 'Borivali Railway Station (East Exit)',
      code: 'BVI',
      line: 'Western Line',
      distance_km: 1.2,
      walking_time_mins: 15,
      road_time_mins: 5,
      transfer_modes: ['Walk', 'Auto Rickshaw', 'BEST Bus'],
    },
  ],
  'juhu-beach': [
    {
      id: 'vile-parle',
      name: 'Vile Parle Station',
      code: 'VLP',
      line: 'Western Line',
      distance_km: 3.2,
      walking_time_mins: 38,
      road_time_mins: 12,
      transfer_modes: ['Auto Rickshaw', 'BEST Bus (231)', 'Taxi'],
    },
    {
      id: 'santacruz',
      name: 'Santacruz Station',
      code: 'STC',
      line: 'Western & Harbour Line',
      distance_km: 3.8,
      walking_time_mins: 45,
      road_time_mins: 14,
      transfer_modes: ['Auto Rickshaw', 'Taxi'],
    },
  ],
  'worli-sea-face': [
    {
      id: 'lower-parel',
      name: 'Lower Parel Station',
      code: 'PL',
      line: 'Western Line',
      distance_km: 2.8,
      walking_time_mins: 35,
      road_time_mins: 10,
      transfer_modes: ['Taxi', 'BEST Bus', 'Auto (Suburbs boundary)'],
    },
    {
      id: 'currey-road',
      name: 'Currey Road Station',
      code: 'CRD',
      line: 'Central Line',
      distance_km: 3.4,
      walking_time_mins: 42,
      road_time_mins: 12,
      transfer_modes: ['Taxi', 'BEST Bus'],
    },
  ],
  'csmvs-museum': [
    {
      id: 'churchgate',
      name: 'Churchgate Station',
      code: 'CCG',
      line: 'Western Line',
      distance_km: 1.4,
      walking_time_mins: 18,
      road_time_mins: 5,
      transfer_modes: ['Walk (through Kala Ghoda art district)', 'Taxi'],
    },
    {
      id: 'csmt',
      name: 'CSMT Station',
      code: 'CSMT',
      line: 'Central Line',
      distance_km: 1.9,
      walking_time_mins: 24,
      road_time_mins: 7,
      transfer_modes: ['Taxi', 'Walk'],
    },
  ],
  'siddhivinayak-temple': [
    {
      id: 'dadar',
      name: 'Dadar Junction (Western & Central)',
      code: 'DDR / DR',
      line: 'Western & Central Main Interchange',
      distance_km: 1.8,
      walking_time_mins: 22,
      road_time_mins: 7,
      transfer_modes: ['Taxi', 'Walk', 'BEST Bus'],
    },
    {
      id: 'prabhadevi',
      name: 'Prabhadevi Station (formerly Elphinstone Rd)',
      code: 'PBHD',
      line: 'Western Line',
      distance_km: 1.3,
      walking_time_mins: 16,
      road_time_mins: 5,
      transfer_modes: ['Walk', 'Taxi'],
    },
  ],
};

export function getNearbyStationsForPlace(placeId: string): RailwayStationInfo[] {
  const cleanId = placeId.trim().toLowerCase();
  if (MUMBAI_RAILWAY_STATIONS[cleanId]) {
    return MUMBAI_RAILWAY_STATIONS[cleanId];
  }
  // Default fallback to Churchgate/CSMT
  return MUMBAI_RAILWAY_STATIONS['gateway-of-india'];
}
