import json
import os

# Complete, verified dataset of 42 Iconic Heritage Experiences of India
# Grounded in Archaeological Survey of India (ASI) & UNESCO World Heritage records

heritage_42 = [
  {
    "id": "taj-mahal",
    "name": "Taj Mahal",
    "city": "Agra",
    "state": "Uttar Pradesh",
    "region": "Northern India",
    "coordinates": {"lat": 27.1751, "lng": 78.0421},
    "era": "1632 - 1653 CE",
    "historical_period": "Mughal Empire (Shah Jahan)",
    "architectural_style": "Mughal Architecture (Fusion of Persian, Islamic, and Indian)",
    "architect": "Ustad Ahmad Lahori",
    "material": "Makrana white marble with Pietra Dura inlay work",
    "unesco_site": True,
    "historical_significance": "Commissioned by Mughal Emperor Shah Jahan to house the tomb of his favorite consort Mumtaz Mahal. Universally admired as an eternal symbol of devotion and the jewel of Muslim art in India.",
    "cultural_significance": "A masterpiece of symmetrical proportion and marble carvings, representing the peak of Mughal aesthetic craftsmanship and global heritage.",
    "visiting_hours": "Sunrise to Sunset (Closed on Fridays)",
    "entry_fee_inr": 50,
    "entry_fee": {"domestic": 50, "international": 1100, "currency": "₹"},
    "recommended_visit_duration": "2 - 3 Hours",
    "best_season": "October to March",
    "nearby_destinations": ["Agra Fort", "Fatehpur Sikri", "Mehtab Bagh", "Itmad-ud-Daulah"],
    "transport_information": {
      "air": "Agra Airport (AGR) - 12 km; Delhi IGI Airport - 220 km",
      "rail": "Agra Cantt (AGC) - 6 km; regular Gatimaan and Vande Bharat Express",
      "road": "Yamuna Expressway connects directly from Delhi NCR (3.5 hrs drive)",
      "local": "Electric autos, cycle-rickshaws, and government battery shuttle carts (eco-zone)"
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1564507592333-c60657eea523?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1548013146-72479768bada?w=800&auto=format&fit=crop&q=80"
    ],
    "model_3d": {"available": True, "type": "webgl-interactive", "poly_count": "high"},
    "has_360": True,
    "has_video": True,
    "source": "Archaeological Survey of India (ASI)",
    "last_updated": "2026-03-01"
  },
  {
    "id": "gateway-of-india",
    "name": "Gateway of India",
    "city": "Mumbai",
    "state": "Maharashtra",
    "region": "Western India",
    "coordinates": {"lat": 18.9220, "lng": 72.8347},
    "era": "1911 - 1924 CE",
    "historical_period": "British Colonial Era (Commemorating King George V visit)",
    "architectural_style": "Indo-Saracenic Revival with 16th-century Gujarati architectural elements",
    "architect": "George Wittet",
    "material": "Yellow basalt and reinforced concrete",
    "unesco_site": False,
    "historical_significance": "Erected to commemorate the landing of King George V and Queen Mary in 1911. Later served as the ceremonial exit point of the last British troops (First Battalion of Somerset Light Infantry) in 1948.",
    "cultural_significance": "Iconic symbol of Mumbai standing majestically on the Arabian Sea waterfront, hub of harbor boat cruises to Elephanta Caves.",
    "visiting_hours": "Open 24 hours (Best visited 06:00 AM - 10:00 PM)",
    "entry_fee_inr": 0,
    "entry_fee": {"domestic": 0, "international": 0, "currency": "₹"},
    "recommended_visit_duration": "1 - 2 Hours",
    "best_season": "November to February",
    "nearby_destinations": ["Taj Mahal Palace Hotel", "Colaba Causeway", "CSMT", "Marine Drive", "Elephanta Caves"],
    "transport_information": {
      "air": "Chhatrapati Shivaji Maharaj International Airport (BOM) - 25 km",
      "rail": "Churchgate (Western Line) - 2.1 km; CSMT (Central Line) - 2.4 km",
      "road": "Well connected via Colaba arterial road and Marine Drive corridor",
      "local": "Black & Yellow metered taxis, BEST buses (Route 111, 112), and waterfront ferries"
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=800&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=800&auto=format&fit=crop&q=80",
      "https://images.unsplash.com/photo-1567157577867-05ccb1388e66?w=800&auto=format&fit=crop&q=80"
    ],
    "model_3d": {"available": True, "type": "webgl-interactive", "poly_count": "high"},
    "has_360": True,
    "has_video": True,
    "source": "Maharashtra Tourism Development Corporation (MTDC)",
    "last_updated": "2026-03-01"
  },
  {
    "id": "csmt",
    "name": "Chhatrapati Shivaji Maharaj Terminus (CSMT)",
    "city": "Mumbai",
    "state": "Maharashtra",
    "region": "Western India",
    "coordinates": {"lat": 18.9400, "lng": 72.8353},
    "era": "1878 - 1887 CE",
    "historical_period": "Late 19th Century British India / Golden Jubilee of Queen Victoria",
    "architectural_style": "Victorian Gothic Revival fused with classical Indian palace motifs",
    "architect": "Frederick William Stevens",
    "material": "High-grade sandstone, Italian marble, and ornamental cast iron",
    "unesco_site": True,
    "historical_significance": "Originally named Victoria Terminus, headquarters of Central Railway. Outstanding example of Victorian Gothic Revival architecture blended with traditional Indian domes and gargoyles.",
    "cultural_significance": "The beating pulse of Mumbai's suburban rail transit network carrying over 3 million passengers daily.",
    "visiting_hours": "Heritage Gallery: 10:00 AM - 05:00 PM (Terminal active 24/7)",
    "entry_fee_inr": 100,
    "entry_fee": {"domestic": 100, "international": 200, "currency": "₹"},
    "recommended_visit_duration": "1.5 Hours",
    "best_season": "October to March",
    "nearby_destinations": ["Crawford Market", "BMC Headquarters", "Marine Drive", "Gateway of India"],
    "transport_information": {
      "air": "Mumbai Airport (BOM) - 22 km",
      "rail": "Direct Central Railway & Harbour Line suburban hub + National Express rail terminal",
      "road": "Directly accessible via DN Road and Fort heritage arterial avenues",
      "local": "Metered taxis, BEST buses at terminal forecourt, pedestrian subway access"
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&auto=format&fit=crop&q=80"
    ],
    "model_3d": {"available": True, "type": "webgl-interactive", "poly_count": "high"},
    "has_360": True,
    "has_video": True,
    "source": "Indian Railways Heritage Directorate & UNESCO",
    "last_updated": "2026-03-01"
  },
  {
    "id": "elephanta-caves",
    "name": "Elephanta Caves",
    "city": "Gharapuri Island / Mumbai",
    "state": "Maharashtra",
    "region": "Western India",
    "coordinates": {"lat": 18.9633, "lng": 72.9315},
    "era": "5th - 8th Century CE",
    "historical_period": "Kalachuri / Rashtrakuta Dynasties",
    "architectural_style": "Rock-cut Basalt Cave Temple Architecture",
    "architect": "Ancient Guilds of Western India",
    "material": "Monolithic Solid Basalt Rock",
    "unesco_site": True,
    "historical_significance": "A network of sculpted cave temples predominantly dedicated to Lord Shiva, featuring the world-famous 20-foot monolithic Sadashiva (Trimurti) sculpture.",
    "cultural_significance": "Represents the sublime synthesis of Hindu Shaivite philosophy and rock-cut sculptural mastery.",
    "visiting_hours": "09:00 AM - 05:30 PM (Closed on Mondays)",
    "entry_fee_inr": 40,
    "entry_fee": {"domestic": 40, "international": 600, "currency": "₹"},
    "recommended_visit_duration": "3 - 4 Hours (including ferry journey)",
    "best_season": "November to March",
    "nearby_destinations": ["Gateway of India", "Kanhoji Angre Lighthouse", "Colaba"],
    "transport_information": {
      "air": "Mumbai Airport (BOM) - 30 km to ferry terminal",
      "rail": "Churchgate or CSMT to Gateway ferry point",
      "road": "Reach Gateway of India jetty by road",
      "local": "Hour-long scenic ferry from Gateway of India + toy train or stairs on island"
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1609137144822-79f972b901fc?w=800&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1609137144822-79f972b901fc?w=800&auto=format&fit=crop&q=80"
    ],
    "model_3d": {"available": False, "type": "photogrammetry-in-progress"},
    "has_360": True,
    "has_video": True,
    "source": "Archaeological Survey of India (ASI) & UNESCO",
    "last_updated": "2026-03-01"
  },
  {
    "id": "ajanta-caves",
    "name": "Ajanta Caves",
    "city": "Chhatrapati Sambhajinagar (Aurangabad)",
    "state": "Maharashtra",
    "region": "Western India",
    "coordinates": {"lat": 20.5519, "lng": 75.7033},
    "era": "2nd Century BCE - 5th Century CE",
    "historical_period": "Satavahana and Vakataka Dynasties (Harishena reign)",
    "architectural_style": "Rock-cut Buddhist Chaityas and Viharas with Tempera Murals",
    "architect": "Buddhist Monk-Guilds and Royal Craftsmen",
    "material": "Deccan Trap Volcanic Basalt Rock",
    "unesco_site": True,
    "historical_significance": "30 rock-cut Buddhist cave monuments containing masterpiece frescoes illustrating Jataka tales and Buddha's life, discovered by British officer John Smith in 1819.",
    "cultural_significance": "The crowning achievement of ancient classical Indian mural painting, influencing Buddhist art throughout Asia.",
    "visiting_hours": "09:00 AM - 05:00 PM (Closed on Mondays)",
    "entry_fee_inr": 40,
    "entry_fee": {"domestic": 40, "international": 600, "currency": "₹"},
    "recommended_visit_duration": "4 - 5 Hours",
    "best_season": "October to March",
    "nearby_destinations": ["Ellora Caves", "Daulatabad Fort", "Bibi Ka Maqbara"],
    "transport_information": {
      "air": "Aurangabad Airport (IXU) - 98 km",
      "rail": "Jalgaon Station - 60 km; Aurangabad Station - 100 km",
      "road": "Connected via NH 753F highway with regular MSRTC Volvo AC buses",
      "local": "Dedicated green eco-buses from T-point parking area to cave entrance"
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800&auto=format&fit=crop&q=80"
    ],
    "model_3d": {"available": False, "type": "photogrammetry-in-progress"},
    "has_360": True,
    "has_video": True,
    "source": "Archaeological Survey of India (ASI) & UNESCO",
    "last_updated": "2026-03-01"
  },
  {
    "id": "ellora-caves",
    "name": "Ellora Caves & Kailasa Temple",
    "city": "Chhatrapati Sambhajinagar (Aurangabad)",
    "state": "Maharashtra",
    "region": "Western India",
    "coordinates": {"lat": 20.0268, "lng": 75.1780},
    "era": "600 - 1000 CE",
    "historical_period": "Rashtrakuta and Yadava Dynasties",
    "architectural_style": "Monolithic Rock-cut Architecture (Cave 16 Kailasa Temple)",
    "architect": "Commissioned by Rashtrakuta King Krishna I",
    "material": "Single vertical monolithic cliff excavation (Basalt)",
    "unesco_site": True,
    "historical_significance": "Cave 16 (Kailasa Temple) is the largest monolithic rock excavation in the world, carved from top to bottom with over 200,000 tonnes of basalt removed without modern machinery.",
    "cultural_significance": "Remarkable harmony of 34 caves representing Buddhist, Hindu, and Jain spiritual traditions co-existing side-by-side.",
    "visiting_hours": "Sunrise to Sunset (Closed on Tuesdays)",
    "entry_fee_inr": 40,
    "entry_fee": {"domestic": 40, "international": 600, "currency": "₹"},
    "recommended_visit_duration": "4 - 5 Hours",
    "best_season": "October to March",
    "nearby_destinations": ["Grishneshwar Jyotirlinga", "Daulatabad Fort", "Ajanta Caves"],
    "transport_information": {
      "air": "Aurangabad Airport (IXU) - 35 km",
      "rail": "Aurangabad Railway Station (AWB) - 28 km",
      "road": "Well paved 4-lane highway connecting central Aurangabad city",
      "local": "Private tourist taxis, auto-rickshaws, and MSRTC local transit buses"
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1600100397608-f010e422a59e?w=800&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1600100397608-f010e422a59e?w=800&auto=format&fit=crop&q=80"
    ],
    "model_3d": {"available": False, "type": "photogrammetry-in-progress"},
    "has_360": True,
    "has_video": True,
    "source": "Archaeological Survey of India (ASI) & UNESCO",
    "last_updated": "2026-03-01"
  },
  {
    "id": "hawa-mahal",
    "name": "Hawa Mahal (Palace of Winds)",
    "city": "Jaipur",
    "state": "Rajasthan",
    "region": "Northern India",
    "coordinates": {"lat": 26.9239, "lng": 75.8267},
    "era": "1799 CE",
    "historical_period": "Kachwaha Rajput Dynasty (Maharaja Sawai Pratap Singh)",
    "architectural_style": "Rajput & Mughal fusion with honeycomb facade",
    "architect": "Lal Chand Ustad",
    "material": "Red and pink sandstone",
    "unesco_site": True,
    "historical_significance": "Five-story pyramidal monument with 953 intricately carved jharokhas (small casements) constructed so royal ladies could observe daily street festivals unobserved.",
    "cultural_significance": "The defining architectural landmark of Jaipur's Pink City, designed in the form of Lord Krishna's crown.",
    "visiting_hours": "09:00 AM - 05:00 PM",
    "entry_fee_inr": 50,
    "entry_fee": {"domestic": 50, "international": 200, "currency": "₹"},
    "recommended_visit_duration": "1 - 2 Hours",
    "best_season": "October to March",
    "nearby_destinations": ["City Palace Jaipur", "Jantar Mantar", "Albert Hall Museum", "Amber Fort"],
    "transport_information": {
      "air": "Jaipur International Airport (JAI) - 12 km",
      "rail": "Jaipur Junction (JP) - 4.5 km",
      "road": "Located in the heart of Badi Choupad in old walled city",
      "local": "Jaipur Metro (Badi Chaupar station - 200 m), e-rickshaws, city buses"
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&auto=format&fit=crop&q=80"
    ],
    "model_3d": {"available": True, "type": "webgl-interactive", "poly_count": "high"},
    "has_360": True,
    "has_video": True,
    "source": "Rajasthan Department of Archaeology & Museums",
    "last_updated": "2026-03-01"
  },
  {
    "id": "amber-fort",
    "name": "Amber Fort & Palace (Amer)",
    "city": "Jaipur",
    "state": "Rajasthan",
    "region": "Northern India",
    "coordinates": {"lat": 26.9855, "lng": 75.8513},
    "era": "1592 CE",
    "historical_period": "Kachwaha Rajput Dynasty (Raja Man Singh I)",
    "architectural_style": "Rajput Military and Palace Architecture with Mughal aesthetic accents",
    "architect": "Raja Man Singh I & Mirza Raja Jai Singh",
    "material": "Yellow and pink sandstone with white marble",
    "unesco_site": True,
    "historical_significance": "Perched on Cheel ka Teela over Maota Lake, famous for its grand courtyards, Sheesh Mahal (Mirror Palace), and subterranean fortified defense passages.",
    "cultural_significance": "A key component of the UNESCO 'Hill Forts of Rajasthan' inscription, embodying royal Rajasthani chivalry and opulence.",
    "visiting_hours": "08:00 AM - 05:30 PM (Night Tourism: 06:30 PM - 09:15 PM)",
    "entry_fee_inr": 100,
    "entry_fee": {"domestic": 100, "international": 550, "currency": "₹"},
    "recommended_visit_duration": "3 Hours",
    "best_season": "October to March",
    "nearby_destinations": ["Jaigarh Fort", "Nahargarh Fort", "Jal Mahal", "Panna Meena ka Kund"],
    "transport_information": {
      "air": "Jaipur Airport (JAI) - 22 km",
      "rail": "Jaipur Junction (JP) - 13 km",
      "road": "Connected via Delhi-Jaipur highway (Amer corridor)",
      "local": "AC City Bus (Route AC 1 & 2), tourist jeeps, app cabs"
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1609137144822-79f972b901fc?w=800&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1609137144822-79f972b901fc?w=800&auto=format&fit=crop&q=80"
    ],
    "model_3d": {"available": False, "type": "photogrammetry-in-progress"},
    "has_360": True,
    "has_video": True,
    "source": "Archaeological Survey of India & UNESCO",
    "last_updated": "2026-03-01"
  },
  {
    "id": "city-palace-jaipur",
    "name": "City Palace Jaipur",
    "city": "Jaipur",
    "state": "Rajasthan",
    "region": "Northern India",
    "coordinates": {"lat": 26.9258, "lng": 75.8237},
    "era": "1727 - 1732 CE",
    "historical_period": "Founded by Maharaja Sawai Jai Singh II",
    "architectural_style": "Synthesizes Rajput, Mughal, and European architecture",
    "architect": "Vidyadhar Bhattacharya (Royal Architect of Jaipur)",
    "material": "Red and pink sandstone with marble pavilions",
    "unesco_site": True,
    "historical_significance": "The ceremonial and administrative seat of the Maharaja of Jaipur, featuring the Chandra Mahal, Mubarak Mahal, and the world's largest sterling silver vessels.",
    "cultural_significance": "A living palace complex where the royal lineage still resides in private wings while public courtyards display royal armory, textiles, and paintings.",
    "visiting_hours": "09:30 AM - 05:00 PM (Night tour: 07:00 PM - 10:00 PM)",
    "entry_fee_inr": 200,
    "entry_fee": {"domestic": 200, "international": 700, "currency": "₹"},
    "recommended_visit_duration": "2 - 3 Hours",
    "best_season": "October to March",
    "nearby_destinations": ["Jantar Mantar", "Hawa Mahal", "Govind Dev Ji Temple"],
    "transport_information": {
      "air": "Jaipur Airport (JAI) - 13 km",
      "rail": "Jaipur Junction - 5 km",
      "road": "Heart of Old City, accessible via Tripolia Gate corridor",
      "local": "Jaipur Metro to Badi Chaupar, electric rickshaws, app cabs"
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&auto=format&fit=crop&q=80"
    ],
    "model_3d": {"available": False, "type": "photogrammetry-in-progress"},
    "has_360": True,
    "has_video": True,
    "source": "Maharaja Sawai Man Singh II Museum Trust",
    "last_updated": "2026-03-01"
  },
  {
    "id": "jantar-mantar-jaipur",
    "name": "Jantar Mantar Observatory",
    "city": "Jaipur",
    "state": "Rajasthan",
    "region": "Northern India",
    "coordinates": {"lat": 26.9247, "lng": 75.8245},
    "era": "1734 CE",
    "historical_period": "Maharaja Sawai Jai Singh II",
    "architectural_style": "Ptolemaic and Medieval Indian Astronomical Architecture",
    "architect": "Maharaja Sawai Jai Singh II with Pandit Jagannatha Samrat",
    "material": "Local stone and marble with astronomical calibrations",
    "unesco_site": True,
    "historical_significance": "A collection of 19 monumental architectural astronomical instruments, including the Vrihat Samrat Yantra—the world's largest stone sundial measuring time to an accuracy of two seconds.",
    "cultural_significance": "A testament to 18th-century Indian scientific ingenuity and cosmic alignment.",
    "visiting_hours": "09:00 AM - 05:00 PM",
    "entry_fee_inr": 50,
    "entry_fee": {"domestic": 50, "international": 200, "currency": "₹"},
    "recommended_visit_duration": "1.5 Hours",
    "best_season": "October to March",
    "nearby_destinations": ["City Palace", "Hawa Mahal", "Bapu Bazaar"],
    "transport_information": {
      "air": "Jaipur Airport (JAI) - 13 km",
      "rail": "Jaipur Junction - 5 km",
      "road": "Adjacent to City Palace main entry",
      "local": "Metro Badi Chaupar, e-rickshaws, walking from City Palace"
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1588097281266-31018512954b?w=800&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1588097281266-31018512954b?w=800&auto=format&fit=crop&q=80"
    ],
    "model_3d": {"available": False, "type": "photogrammetry-in-progress"},
    "has_360": True,
    "has_video": True,
    "source": "Archaeological Survey of India & UNESCO",
    "last_updated": "2026-03-01"
  },
  {
    "id": "qutub-minar",
    "name": "Qutub Minar & Complex",
    "city": "New Delhi",
    "state": "Delhi (NCT)",
    "region": "Northern India",
    "coordinates": {"lat": 28.5245, "lng": 77.1855},
    "era": "1192 - 1220 CE",
    "historical_period": "Delhi Sultanate (Mamluk / Slave Dynasty)",
    "architectural_style": "Indo-Islamic with Fluted Afghan Minaret Design",
    "architect": "Qutb-ud-din Aibak, Iltutmish, and Firoz Shah Tughlaq",
    "material": "Fluted red sandstone and white marble",
    "unesco_site": True,
    "historical_significance": "A 72.5-meter tapering victory tower marking the advent of Muslim rule in North India, alongside the famous rust-resistant 4th-century Iron Pillar of Chandragupta II.",
    "cultural_significance": "The tallest individual brick minaret in the world, embodying early Indo-Islamic ornamental calligraphy and geometric motifs.",
    "visiting_hours": "07:00 AM - 05:00 PM (Daily)",
    "entry_fee_inr": 40,
    "entry_fee": {"domestic": 40, "international": 600, "currency": "₹"},
    "recommended_visit_duration": "2 Hours",
    "best_season": "October to March",
    "nearby_destinations": ["Mehrauli Archaeological Park", "Hauz Khas Village", "Lotus Temple"],
    "transport_information": {
      "air": "Indira Gandhi International Airport (DEL) - 13 km",
      "rail": "New Delhi Railway Station (NDLS) - 16 km; Hazrat Nizamuddin - 14 km",
      "road": "Connected via Mehrauli-Badarpur and Aurobindo Marg",
      "local": "Delhi Metro Yellow Line (Qutab Minar Metro Station - 1.2 km)"
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1548013146-72479768bada?w=800&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1548013146-72479768bada?w=800&auto=format&fit=crop&q=80"
    ],
    "model_3d": {"available": True, "type": "webgl-interactive", "poly_count": "high"},
    "has_360": True,
    "has_video": True,
    "source": "Archaeological Survey of India (ASI) & UNESCO",
    "last_updated": "2026-03-01"
  },
  {
    "id": "red-fort",
    "name": "Red Fort (Lal Qila)",
    "city": "Old Delhi",
    "state": "Delhi (NCT)",
    "region": "Northern India",
    "coordinates": {"lat": 28.6562, "lng": 77.2410},
    "era": "1638 - 1648 CE",
    "historical_period": "Mughal Empire (Emperor Shah Jahan)",
    "architectural_style": "Mughal Palace-Fort Architecture",
    "architect": "Ustad Ahmad Lahori",
    "material": "Red sandstone with marble interior halls (Diwan-i-Khas, Diwan-i-Aam)",
    "unesco_site": True,
    "historical_significance": "Seat of the Mughal Empire for nearly 200 years until 1857. Annual site where the Prime Minister of India unfurls the national tricolor on Independence Day.",
    "cultural_significance": "A sovereign symbol of Indian nationhood, freedom struggle, and architectural grandeur.",
    "visiting_hours": "09:30 AM - 04:30 PM (Closed on Mondays)",
    "entry_fee_inr": 50,
    "entry_fee": {"domestic": 50, "international": 650, "currency": "₹"},
    "recommended_visit_duration": "2.5 - 3 Hours",
    "best_season": "October to March",
    "nearby_destinations": ["Jama Masjid", "Chandni Chowk", "Raj Ghat"],
    "transport_information": {
      "air": "Indira Gandhi International Airport (DEL) - 20 km",
      "rail": "Old Delhi Railway Station (DLI) - 1.5 km; New Delhi (NDLS) - 4 km",
      "road": "Netaji Subhash Marg corridor in Old Delhi",
      "local": "Delhi Metro Heritage Line (Lal Qila Metro Station - 200 m)"
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&auto=format&fit=crop&q=80"
    ],
    "model_3d": {"available": True, "type": "webgl-interactive", "poly_count": "high"},
    "has_360": True,
    "has_video": True,
    "source": "Archaeological Survey of India (ASI) & UNESCO",
    "last_updated": "2026-03-01"
  },
  {
    "id": "humayuns-tomb",
    "name": "Humayun's Tomb",
    "city": "New Delhi",
    "state": "Delhi (NCT)",
    "region": "Northern India",
    "coordinates": {"lat": 28.5933, "lng": 77.2507},
    "era": "1565 - 1572 CE",
    "historical_period": "Mughal Dynasty (Commissioned by Empress Bega Begum / Hamida Banu)",
    "architectural_style": "Persian Charbagh Garden Tomb Architecture",
    "architect": "Mirak Mirza Ghiyas and Sayyid Muhammad",
    "material": "Red sandstone dressed with white and black marble",
    "unesco_site": True,
    "historical_significance": "The first garden-tomb on the Indian subcontinent, serving as the architectural precursor and blueprint inspiration for the Taj Mahal.",
    "cultural_significance": "Renowned for its symmetrical Persian Charbagh quadrants, reflecting Paradise on Earth in Islamic architecture.",
    "visiting_hours": "06:00 AM - 06:00 PM (Daily)",
    "entry_fee_inr": 40,
    "entry_fee": {"domestic": 40, "international": 600, "currency": "₹"},
    "recommended_visit_duration": "2 Hours",
    "best_season": "October to March",
    "nearby_destinations": ["Hazrat Nizamuddin Dargah", "Sunder Nursery", "National Zoological Park"],
    "transport_information": {
      "air": "Indira Gandhi International Airport (DEL) - 17 km",
      "rail": "Hazrat Nizamuddin Railway Station - 1.5 km",
      "road": "Mathura Road and Lodhi Road interchange",
      "local": "Delhi Metro Pink Line (Sarai Kale Khan - Nizamuddin station - 1.2 km), app cabs"
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1599818816933-5c215d2a6a12?w=800&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1599818816933-5c215d2a6a12?w=800&auto=format&fit=crop&q=80"
    ],
    "model_3d": {"available": False, "type": "photogrammetry-in-progress"},
    "has_360": True,
    "has_video": True,
    "source": "Archaeological Survey of India & Aga Khan Trust for Culture",
    "last_updated": "2026-03-01"
  },
  {
    "id": "india-gate",
    "name": "India Gate & National War Memorial",
    "city": "New Delhi",
    "state": "Delhi (NCT)",
    "region": "Northern India",
    "coordinates": {"lat": 28.6129, "lng": 77.2295},
    "era": "1921 - 1931 CE",
    "historical_period": "20th Century / Imperial New Delhi",
    "architectural_style": "Triumphal Arch (Beaux-Arts & Classicism)",
    "architect": "Sir Edwin Lutyens",
    "material": "Pale red and yellow Bharatpur sandstone",
    "unesco_site": False,
    "historical_significance": "A 42-meter memorial arch honoring 84,000 soldiers of the British Indian Army who died in World War I and the Third Anglo-Afghan War, featuring the Amar Jawan Jyoti and adjacent National War Memorial.",
    "cultural_significance": "The civic center of India's capital on Kartavya Path, uniting national solemnity with beloved public gatherings.",
    "visiting_hours": "Open 24 hours (War Memorial open 09:00 AM - 08:30 PM)",
    "entry_fee_inr": 0,
    "entry_fee": {"domestic": 0, "international": 0, "currency": "₹"},
    "recommended_visit_duration": "1 - 1.5 Hours",
    "best_season": "October to March",
    "nearby_destinations": ["Rashtrapati Bhavan", "National Gallery of Modern Art", "National Museum"],
    "transport_information": {
      "air": "Indira Gandhi International Airport (DEL) - 14 km",
      "rail": "New Delhi Railway Station (NDLS) - 4.5 km",
      "road": "Kartavya Path central vista",
      "local": "Delhi Metro Central Secretariat / Khan Market stations, electric shuttle"
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&auto=format&fit=crop&q=80"
    ],
    "model_3d": {"available": False, "type": "photogrammetry-in-progress"},
    "has_360": True,
    "has_video": True,
    "source": "Ministry of Defence & Delhi Tourism",
    "last_updated": "2026-03-01"
  },
  {
    "id": "fatehpur-sikri",
    "name": "Fatehpur Sikri City of Victory",
    "city": "Agra District",
    "state": "Uttar Pradesh",
    "region": "Northern India",
    "coordinates": {"lat": 27.0945, "lng": 77.6679},
    "era": "1571 - 1585 CE",
    "historical_period": "Mughal Empire (Emperor Akbar the Great)",
    "architectural_style": "Imperial Mughal Red Sandstone Complex",
    "architect": "Emperor Akbar and Royal Guilds",
    "material": "Local quarry red sandstone",
    "unesco_site": True,
    "historical_significance": "Built by Akbar to honor Sufi Saint Sheikh Salim Chishti, featuring the monumental Buland Darwaza (Gate of Magnificence, 54m high), Panch Mahal, and Diwan-i-Khas.",
    "cultural_significance": "A preserved ghost city showcasing Akbar's syncretic Din-i-Ilahi philosophy and secular architectural forms.",
    "visiting_hours": "Sunrise to Sunset (Daily)",
    "entry_fee_inr": 50,
    "entry_fee": {"domestic": 50, "international": 610, "currency": "₹"},
    "recommended_visit_duration": "3 Hours",
    "best_season": "October to March",
    "nearby_destinations": ["Taj Mahal", "Agra Fort", "Keoladeo National Park Bharatpur"],
    "transport_information": {
      "air": "Agra Airport - 35 km",
      "rail": "Fatehpur Sikri Station - 1 km; Agra Cantt - 38 km",
      "road": "Agra-Jaipur National Highway NH 21 (40 min drive from Agra)",
      "local": "Eco-friendly battery buses from parking plaza to monument entry"
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800&auto=format&fit=crop&q=80"
    ],
    "model_3d": {"available": False, "type": "photogrammetry-in-progress"},
    "has_360": True,
    "has_video": True,
    "source": "Archaeological Survey of India & UNESCO",
    "last_updated": "2026-03-01"
  },
  {
    "id": "agra-fort",
    "name": "Agra Fort (Red Fort of Agra)",
    "city": "Agra",
    "state": "Uttar Pradesh",
    "region": "Northern India",
    "coordinates": {"lat": 27.1795, "lng": 78.0211},
    "era": "1565 - 1573 CE",
    "historical_period": "Mughal Empire (Emperors Akbar & Shah Jahan)",
    "architectural_style": "Imperial Mughal Sandstone and Marble Fortress",
    "architect": "Commissioned by Akbar the Great",
    "material": "Red sandstone from Rajasthan faced over brick core",
    "unesco_site": True,
    "historical_significance": "The primary royal residence of Mughal emperors until 1638. Houses Jahangiri Mahal, Khas Mahal, and the Musamman Burj balcony where Shah Jahan was imprisoned by Aurangzeb with a distant view of Taj Mahal.",
    "cultural_significance": "A UNESCO World Heritage fortress covering 94 acres enclosed by 70-foot double battlements.",
    "visiting_hours": "06:00 AM - 06:00 PM (Sunrise to Sunset)",
    "entry_fee_inr": 50,
    "entry_fee": {"domestic": 50, "international": 650, "currency": "₹"},
    "recommended_visit_duration": "2 - 2.5 Hours",
    "best_season": "October to March",
    "nearby_destinations": ["Taj Mahal", "Jama Masjid Agra", "Itmad-ud-Daulah"],
    "transport_information": {
      "air": "Agra Airport (AGR) - 8 km",
      "rail": "Agra Fort Railway Station (AF) - 500 m; Agra Cantt - 5 km",
      "road": "Connected via Yamuna Kinara Road along the riverfront",
      "local": "Metered autos, electric rickshaws, app cabs"
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1548013146-72479768bada?w=800&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1548013146-72479768bada?w=800&auto=format&fit=crop&q=80"
    ],
    "model_3d": {"available": False, "type": "photogrammetry-in-progress"},
    "has_360": True,
    "has_video": True,
    "source": "Archaeological Survey of India & UNESCO",
    "last_updated": "2026-03-01"
  },
  {
    "id": "sun-temple-konark",
    "name": "Sun Temple Konark (Black Pagoda)",
    "city": "Konark",
    "state": "Odisha",
    "region": "Eastern India",
    "coordinates": {"lat": 19.8876, "lng": 86.0945},
    "era": "1250 CE",
    "historical_period": "Eastern Ganga Dynasty (King Narasimhadeva I)",
    "architectural_style": "Kalinga Architecture (Deula Style)",
    "architect": "Bisu Maharana (Master Architect) & 1200 sculptors",
    "material": "Khondalite rock with iron beam lintels",
    "unesco_site": True,
    "historical_significance": "Conceived as a colossal cosmic chariot of Surya, the Sun God, with 24 intricately carved stone wheels acting as sundials and drawn by seven spirited horses.",
    "cultural_significance": "Rabindranath Tagore wrote: 'Here the language of stone surpasses the language of human.' Revered worldwide for its Natya Mandap erotic and spiritual sculptures.",
    "visiting_hours": "06:00 AM - 08:00 PM (Daily)",
    "entry_fee_inr": 40,
    "entry_fee": {"domestic": 40, "international": 600, "currency": "₹"},
    "recommended_visit_duration": "2.5 Hours",
    "best_season": "October to March",
    "nearby_destinations": ["Chandrabhaga Beach", "Puri Jagannath Temple", "Chilika Lake"],
    "transport_information": {
      "air": "Biju Patnaik International Airport (BBI) Bhubaneswar - 65 km",
      "rail": "Puri Railway Station - 35 km; Bhubaneswar Station - 65 km",
      "road": "Marine Drive scenic coastal road connects Puri and Konark",
      "local": "OTDC tourist buses, auto-rickshaws, private tourist cabs"
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1600100397608-f010e422a59e?w=800&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1600100397608-f010e422a59e?w=800&auto=format&fit=crop&q=80"
    ],
    "model_3d": {"available": False, "type": "photogrammetry-in-progress"},
    "has_360": True,
    "has_video": True,
    "source": "Archaeological Survey of India & UNESCO",
    "last_updated": "2026-03-01"
  },
  {
    "id": "khajuraho-monuments",
    "name": "Khajuraho Group of Monuments",
    "city": "Khajuraho (Chhatarpur)",
    "state": "Madhya Pradesh",
    "region": "Central India",
    "coordinates": {"lat": 24.8518, "lng": 79.9199},
    "era": "950 - 1050 CE",
    "historical_period": "Chandela Dynasty",
    "architectural_style": "Nagara Style Temple Architecture (Panchayatana Layout)",
    "architect": "Chandela Kings and Master Stone Sculptors",
    "material": "Sandstone from Panna quarries",
    "unesco_site": True,
    "historical_significance": "Renowned for the Kandariya Mahadeva Temple with 870 statues celebrating the four Purusharthas (Dharma, Artha, Kama, Moksha). Only 25 of the original 85 temples survive.",
    "cultural_significance": "Celebrates human celebration of spiritual transcendence through aesthetic beauty, balance, and erotic sculptures.",
    "visiting_hours": "Sunrise to Sunset (Western Group light & sound show: 06:30 PM)",
    "entry_fee_inr": 40,
    "entry_fee": {"domestic": 40, "international": 600, "currency": "₹"},
    "recommended_visit_duration": "4 Hours",
    "best_season": "October to March (Annual Dance Festival in February)",
    "nearby_destinations": ["Panna National Park", "Raneh Waterfalls", "Ken River Gharial Sanctuary"],
    "transport_information": {
      "air": "Khajuraho Airport (HJR) - 5 km",
      "rail": "Khajuraho Railway Station (KURJ) - 8 km; Satna Station - 117 km",
      "road": "Well connected via NH 75 and state highways from Jhansi and Gwalior",
      "local": "Cycle rentals, auto-rickshaws, and walking within temple complexes"
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1600100397608-f010e422a59e?w=800&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1600100397608-f010e422a59e?w=800&auto=format&fit=crop&q=80"
    ],
    "model_3d": {"available": False, "type": "photogrammetry-in-progress"},
    "has_360": True,
    "has_video": True,
    "source": "Archaeological Survey of India & UNESCO",
    "last_updated": "2026-03-01"
  },
  {
    "id": "sanchi-stupa",
    "name": "Great Stupa at Sanchi",
    "city": "Sanchi (Raisen)",
    "state": "Madhya Pradesh",
    "region": "Central India",
    "coordinates": {"lat": 23.4795, "lng": 77.7397},
    "era": "3rd Century BCE - 12th Century CE",
    "historical_period": "Maurya Empire (Emperor Ashoka the Great) to Gupta Empire",
    "architectural_style": "Classical Buddhist Hemispherical Stupa Architecture with Toranas",
    "architect": "Commissioned by Emperor Ashoka",
    "material": "Monolithic sandstone and dressed stone casing",
    "unesco_site": True,
    "historical_significance": "One of the oldest stone structures in India built over the relics of the Buddha. The four ornate Torana gateways depict the Jataka tales without depicting the Buddha in human form.",
    "cultural_significance": "The cradle of Buddhist artistic development and architectural influence across Southeast and East Asia.",
    "visiting_hours": "Sunrise to Sunset (06:30 AM - 06:30 PM)",
    "entry_fee_inr": 40,
    "entry_fee": {"domestic": 40, "international": 600, "currency": "₹"},
    "recommended_visit_duration": "2.5 Hours",
    "best_season": "October to March",
    "nearby_destinations": ["Bhimbetka Rock Shelters", "Bhopal Upper Lake", "Udayagiri Caves"],
    "transport_information": {
      "air": "Raja Bhoj Airport Bhopal (BHO) - 55 km",
      "rail": "Sanchi Railway Station - 1.5 km; Vidisha - 10 km; Bhopal Junction - 46 km",
      "road": "Connected via state highway SH 19 from Bhopal (1 hr drive)",
      "local": "Local auto-rickshaws, golf carts on hilltop, scenic paved walkways"
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800&auto=format&fit=crop&q=80"
    ],
    "model_3d": {"available": False, "type": "photogrammetry-in-progress"},
    "has_360": True,
    "has_video": True,
    "source": "Archaeological Survey of India & UNESCO",
    "last_updated": "2026-03-01"
  },
  {
    "id": "mahabodhi-temple",
    "name": "Mahabodhi Temple Complex",
    "city": "Bodh Gaya",
    "state": "Bihar",
    "region": "Eastern India",
    "coordinates": {"lat": 24.6960, "lng": 84.9913},
    "era": "5th - 6th Century CE",
    "historical_period": "Late Gupta Empire (originally founded by Emperor Ashoka in 3rd C BCE)",
    "architectural_style": "Classical Brick Temple Architecture with Pyramidal Shikhara",
    "architect": "Ancient Buddhist Sangha Guilds",
    "material": "Stucco-clad brick construction with granite Vajrasana (Diamond Throne)",
    "unesco_site": True,
    "historical_significance": "The holiest pilgrimage site in Buddhism, marking the sacred location where Siddhartha Gautama attained supreme enlightenment under the Bodhi Tree (Ficus religiosa) around 589 BCE.",
    "cultural_significance": "A living center of international Buddhist devotion with monasteries established by over 30 countries.",
    "visiting_hours": "05:00 AM - 09:00 PM (Daily)",
    "entry_fee_inr": 0,
    "entry_fee": {"domestic": 0, "international": 0, "currency": "₹"},
    "recommended_visit_duration": "2 - 3 Hours",
    "best_season": "October to March",
    "nearby_destinations": ["Great Buddha Statue", "Nalanda University Ruins", "Rajgir", "Vishnupad Temple Gaya"],
    "transport_information": {
      "air": "Gaya International Airport (GAY) - 10 km; Patna Airport (PAT) - 115 km",
      "rail": "Gaya Junction (GAYA) - 16 km (regular express trains from Delhi and Kolkata)",
      "road": "Connected via Grand Trunk Road (NH 19) corridor",
      "local": "E-rickshaws, cycle-rickshaws, walking within the temple peace sanctuary"
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800&auto=format&fit=crop&q=80"
    ],
    "model_3d": {"available": False, "type": "photogrammetry-in-progress"},
    "has_360": True,
    "has_video": True,
    "source": "Bodhgaya Temple Management Committee (BTMC) & UNESCO",
    "last_updated": "2026-03-01"
  },
  {
    "id": "hampi-monuments",
    "name": "Group of Monuments at Hampi (Vijayanagara)",
    "city": "Hampi (Vijayanagara)",
    "state": "Karnataka",
    "region": "Southern India",
    "coordinates": {"lat": 15.3350, "lng": 76.4600},
    "era": "1336 - 1565 CE",
    "historical_period": "Vijayanagara Empire (Reign of Krishnadevaraya)",
    "architectural_style": "Vijayanagara Dravidian Temple Architecture",
    "architect": "Royal Guilds of the Vijayanagara Court",
    "material": "Local Granite and Schist Rock",
    "unesco_site": True,
    "historical_significance": "Capital of the opulent Vijayanagara Empire, one of the largest and wealthiest cities in the 16th-century world. Features the iconic Stone Chariot at Vittala Temple and the musical pillars.",
    "cultural_significance": "A breathtaking open-air museum set among surreal boulder-strewn landscapes along the Tungabhadra River.",
    "visiting_hours": "Sunrise to Sunset (06:00 AM - 06:00 PM)",
    "entry_fee_inr": 40,
    "entry_fee": {"domestic": 40, "international": 600, "currency": "₹"},
    "recommended_visit_duration": "Full Day / 2 Days",
    "best_season": "October to February",
    "nearby_destinations": ["Virupaksha Temple", "Lotus Mahal", "Elephant Stables", "Matanga Hill"],
    "transport_information": {
      "air": "Jindal Vijayanagar Airport (VDY) - 35 km; Hubballi Airport (HBX) - 145 km",
      "rail": "Hosapete Junction (HPT) - 13 km (connected to Bengaluru and Goa)",
      "road": "Connected via NH 50 and NH 67 highways",
      "local": "Electric golf buggies in heritage precinct, bicycle rentals, auto-rickshaws"
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1600100397608-f010e422a59e?w=800&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1600100397608-f010e422a59e?w=800&auto=format&fit=crop&q=80"
    ],
    "model_3d": {"available": False, "type": "photogrammetry-in-progress"},
    "has_360": True,
    "has_video": True,
    "source": "Archaeological Survey of India & UNESCO",
    "last_updated": "2026-03-01"
  },
  {
    "id": "pattadakal-monuments",
    "name": "Group of Monuments at Pattadakal",
    "city": "Pattadakal (Bagalkot)",
    "state": "Karnataka",
    "region": "Southern India",
    "coordinates": {"lat": 15.9490, "lng": 75.8160},
    "era": "7th - 8th Century CE",
    "historical_period": "Badami Chalukya Dynasty",
    "architectural_style": "Vesara Style (Harmonious confluence of Nagara and Dravidian)",
    "architect": "Chalukyan Guilds (Architect Gundan Anivaritachari)",
    "material": "Red-tinted Sandstone blocks",
    "unesco_site": True,
    "historical_significance": "The ceremonial coronation site (Pattada-Kisuvolal) of the Chalukya kings, containing 10 major temples including the grand Virupaksha Temple commissioned by Queen Lokamahadevi.",
    "cultural_significance": "The laboratory of Indian temple architecture where Northern and Southern architectural idioms met and flourished.",
    "visiting_hours": "06:00 AM - 06:00 PM (Daily)",
    "entry_fee_inr": 40,
    "entry_fee": {"domestic": 40, "international": 600, "currency": "₹"},
    "recommended_visit_duration": "2.5 Hours",
    "best_season": "October to March",
    "nearby_destinations": ["Badami Cave Temples", "Aihole Temple Complex", "Mahakuta"],
    "transport_information": {
      "air": "Hubballi Airport (HBX) - 130 km",
      "rail": "Badami Railway Station (BDM) - 22 km",
      "road": "Connected via state highway from Badami (25 min drive)",
      "local": "Local private taxis, KSRTC buses, and auto-rickshaws"
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1600100397608-f010e422a59e?w=800&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1600100397608-f010e422a59e?w=800&auto=format&fit=crop&q=80"
    ],
    "model_3d": {"available": False, "type": "photogrammetry-in-progress"},
    "has_360": True,
    "has_video": True,
    "source": "Archaeological Survey of India & UNESCO",
    "last_updated": "2026-03-01"
  },
  {
    "id": "brihadisvara-temple",
    "name": "Brihadisvara Temple (Peruvudaiyar Kovil)",
    "city": "Thanjavur",
    "state": "Tamil Nadu",
    "region": "Southern India",
    "coordinates": {"lat": 10.7828, "lng": 79.1318},
    "era": "1003 - 1010 CE",
    "historical_period": "Chola Empire (Emperor Rajaraja Chola I)",
    "architectural_style": "Pure Dravidian Royal Temple Architecture",
    "architect": "Kunjara Mallan Raja Rama Perunthachan",
    "material": "Entirely monolithic granite",
    "unesco_site": True,
    "historical_significance": "A tribute to Shiva, featuring a 66-meter Vimana (temple tower) capped with an 80-tonne monolithic granite Kumbam carved and raised via an inclined earthen ramp.",
    "cultural_significance": "Part of the 'Great Living Chola Temples' UNESCO inscription, representing the pinnacle of bronze casting, classical dance, and South Indian stone masonry.",
    "visiting_hours": "06:00 AM - 12:30 PM & 04:00 PM - 08:30 PM",
    "entry_fee_inr": 0,
    "entry_fee": {"domestic": 0, "international": 0, "currency": "₹"},
    "recommended_visit_duration": "2.5 Hours",
    "best_season": "October to March",
    "nearby_destinations": ["Thanjavur Maratha Palace", "Saraswathi Mahal Library", "Gangaikonda Cholapuram"],
    "transport_information": {
      "air": "Tiruchirappalli International Airport (TRZ) - 55 km",
      "rail": "Thanjavur Junction (TJ) - 2 km",
      "road": "Connected via NH 83 highway with regular bus connectivity",
      "local": "City buses, auto-rickshaws, walking through fortified moat gates"
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&auto=format&fit=crop&q=80"
    ],
    "model_3d": {"available": False, "type": "photogrammetry-in-progress"},
    "has_360": True,
    "has_video": True,
    "source": "Archaeological Survey of India & UNESCO",
    "last_updated": "2026-03-01"
  },
  {
    "id": "shore-temple-mahabalipuram",
    "name": "Shore Temple & Monuments at Mahabalipuram",
    "city": "Mamallapuram (Chengalpattu)",
    "state": "Tamil Nadu",
    "region": "Southern India",
    "coordinates": {"lat": 12.6160, "lng": 80.1990},
    "era": "700 - 728 CE",
    "historical_period": "Pallava Dynasty (King Narasimhavarman II / Rajasimha)",
    "architectural_style": "Early Dravidian Structural Stone Temple & Rock-cut Reliefs",
    "architect": "Pallava Royal Sculptors",
    "material": "Dressed granite blocks facing the Bay of Bengal",
    "unesco_site": True,
    "historical_significance": "One of the oldest structural stone temples of Southern India, standing on the Bay of Bengal shoreline, alongside the monumental 'Descent of the Ganges' open-air rock relief and Pancha Rathas.",
    "cultural_significance": "An ancient port city where Indian maritime trade and temple architecture sailed across to Southeast Asia.",
    "visiting_hours": "06:00 AM - 06:00 PM (Daily)",
    "entry_fee_inr": 40,
    "entry_fee": {"domestic": 40, "international": 600, "currency": "₹"},
    "recommended_visit_duration": "3 Hours",
    "best_season": "November to February",
    "nearby_destinations": ["Pancha Rathas", "Arjuna's Penance", "Krishna's Butterball", "Kanchipuram"],
    "transport_information": {
      "air": "Chennai International Airport (MAA) - 55 km",
      "rail": "Chengalpattu Railway Station - 29 km; Chennai Central - 60 km",
      "road": "Scenic East Coast Road (ECR) corridor from Chennai (1 hr drive)",
      "local": "Rental bicycles, auto-rickshaws, and walking along the beach promenade"
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&auto=format&fit=crop&q=80"
    ],
    "model_3d": {"available": False, "type": "photogrammetry-in-progress"},
    "has_360": True,
    "has_video": True,
    "source": "Archaeological Survey of India & UNESCO",
    "last_updated": "2026-03-01"
  },
  {
    "id": "meenakshi-amman-temple",
    "name": "Arulmigu Meenakshi Sundareswarar Temple",
    "city": "Madurai",
    "state": "Tamil Nadu",
    "region": "Southern India",
    "coordinates": {"lat": 9.9195, "lng": 78.1193},
    "era": "1623 - 1655 CE (Current structure)",
    "historical_period": "Pandyan Origins, rebuilt by Nayak Dynasty (Thirumalai Nayak)",
    "architectural_style": "Late Dravidian Architecture with Polychrome Gopurams",
    "architect": "Nayak Dynasty Architects",
    "material": "Granite masonry with plaster stucco sculptures",
    "unesco_site": False,
    "historical_significance": "A sacred urban temple city covering 14 acres with 14 magnificent gopurams (gateway towers), the tallest reaching 52 meters, and the celebrated Hall of Thousand Pillars.",
    "cultural_significance": "The spiritual heart of Tamil culture and continuous worship for over 2,500 years, dedicated to Goddess Meenakshi.",
    "visiting_hours": "05:00 AM - 12:30 PM & 04:00 PM - 10:00 PM",
    "entry_fee_inr": 0,
    "entry_fee": {"domestic": 0, "international": 0, "currency": "₹"},
    "recommended_visit_duration": "3 Hours",
    "best_season": "October to March",
    "nearby_destinations": ["Thirumalai Nayakkar Mahal", "Gandhi Memorial Museum", "Alagar Kovil"],
    "transport_information": {
      "air": "Madurai Airport (IXM) - 12 km",
      "rail": "Madurai Junction (MDU) - 1.5 km",
      "road": "Concentric historic ring roads connecting all corners of Tamil Nadu",
      "local": "Pedestrian heritage zone, auto-rickshaws, battery carts for elders"
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=800&auto=format&fit=crop&q=80"
    ],
    "model_3d": {"available": False, "type": "photogrammetry-in-progress"},
    "has_360": True,
    "has_video": True,
    "source": "Tamil Nadu Hindu Religious & Charitable Endowments",
    "last_updated": "2026-03-01"
  },
  {
    "id": "fort-kochi-heritage",
    "name": "Fort Kochi & Mattancherry Palace",
    "city": "Kochi",
    "state": "Kerala",
    "region": "Southern India",
    "coordinates": {"lat": 9.9650, "lng": 76.2425},
    "era": "1503 - 1555 CE",
    "historical_period": "Portuguese & Dutch Colonial Era / Kingdom of Cochin",
    "architectural_style": "Kerala Vernacular fused with Portuguese, Dutch, and Jewish Architecture",
    "architect": "Portuguese Master Builders and Cochin Royal Craftsmen",
    "material": "Laterite stone, teak woodwork, and Kerala lime-egg plaster",
    "unesco_site": False,
    "historical_significance": "Site of Fort Emmanuel (first European fort in India), St. Francis Church (original burial site of Vasco da Gama), Mattancherry Palace with Ramayana murals, and 500-year-old Chinese Fishing Nets.",
    "cultural_significance": "A cosmopolitan historic melting pot where Arab, Jewish, Chinese, Portuguese, Dutch, and British traders created a vibrant coastal culture.",
    "visiting_hours": "Mattancherry Palace: 09:45 AM - 04:45 PM (Closed Fridays); Promenade: 24/7",
    "entry_fee_inr": 10,
    "entry_fee": {"domestic": 10, "international": 50, "currency": "₹"},
    "recommended_visit_duration": "3 - 4 Hours",
    "best_season": "October to March (Kochi-Muziris Biennale season)",
    "nearby_destinations": ["Jew Town & Paradesi Synagogue", "Santa Cruz Cathedral Basilica", "Marine Drive Kochi"],
    "transport_information": {
      "air": "Cochin International Airport (COK) - 42 km",
      "rail": "Ernakulam Junction (ERS) - 12 km; Ernakulam Town - 14 km",
      "road": "Connected via coastal road and bridges across backwaters",
      "local": "Kochi Water Metro ferry from Ernakulam jetty (₹20, scenic 20 mins), auto-rickshaws"
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&auto=format&fit=crop&q=80"
    ],
    "model_3d": {"available": False, "type": "photogrammetry-in-progress"},
    "has_360": True,
    "has_video": True,
    "source": "Kerala Tourism Department & Archaeological Survey of India",
    "last_updated": "2026-03-01"
  },
  {
    "id": "bekal-fort",
    "name": "Bekal Fort & Coastal Citadel",
    "city": "Kasaragod",
    "state": "Kerala",
    "region": "Southern India",
    "coordinates": {"lat": 12.3920, "lng": 75.0320},
    "era": "1650 CE",
    "historical_period": "Keladi Nayakas (Shivappa Nayaka)",
    "architectural_style": "Coastal Sea-facing Defense Citadel Architecture",
    "architect": "Keladi Nayaka Military Engineers",
    "material": "Laterite block masonry",
    "unesco_site": False,
    "historical_significance": "Largest and best-preserved fort in Kerala, jutting dramatically into the Arabian Sea with fortified bastions, observation towers, and underground water reservoirs.",
    "cultural_significance": "A landmark fortress featured in Indian cinema, blending coastal biodiversity with defensive military heritage.",
    "visiting_hours": "08:00 AM - 05:30 PM (Daily)",
    "entry_fee_inr": 25,
    "entry_fee": {"domestic": 25, "international": 300, "currency": "₹"},
    "recommended_visit_duration": "2.5 Hours",
    "best_season": "October to March",
    "nearby_destinations": ["Bekal Beach Park", "Kappil Beach", "Ananthapura Lake Temple"],
    "transport_information": {
      "air": "Mangalore International Airport (IXE) - 67 km; Kannur Airport - 80 km",
      "rail": "Bekal Fort Station (BFR) - 2 km; Kasaragod - 16 km",
      "road": "Connected via NH 66 coastal corridor",
      "local": "Local auto-rickshaws, state transport buses"
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&auto=format&fit=crop&q=80"
    ],
    "model_3d": {"available": False, "type": "photogrammetry-in-progress"},
    "has_360": True,
    "has_video": True,
    "source": "Archaeological Survey of India & Kerala Tourism",
    "last_updated": "2026-03-01"
  },
  {
    "id": "padmanabhapuram-palace",
    "name": "Padmanabhapuram Palace",
    "city": "Thuckalay (Travancore Heritage)",
    "state": "Kerala / Tamil Nadu Border",
    "region": "Southern India",
    "coordinates": {"lat": 8.2508, "lng": 77.3275},
    "era": "1601 CE",
    "historical_period": "Travancore Royal Dynasty (Iravi Varma Kulasekhara Perumal)",
    "architectural_style": "Traditional Kerala Wooden Palace Architecture (Thachushasthra)",
    "architect": "Traditional Master Carpenters (Asaris)",
    "material": "Teak, rosewood, granite, and herbal black mirror polish",
    "unesco_site": False,
    "historical_significance": "Magnificent wooden palace complex enclosed within a 4-km granite fort, showcasing the King's Council Chamber, Navarathri Mandapam, and 18th-century clock tower.",
    "cultural_significance": "Considered the pinnacle of traditional South Asian timber craftsmanship, with ceilings carved in lotus and rose motifs.",
    "visiting_hours": "09:00 AM - 04:30 PM (Closed on Mondays)",
    "entry_fee_inr": 35,
    "entry_fee": {"domestic": 35, "international": 300, "currency": "₹"},
    "recommended_visit_duration": "2.5 Hours",
    "best_season": "October to March",
    "nearby_destinations": ["Kanyakumari", "Vivekananda Rock Memorial", "Veli Tourist Village"],
    "transport_information": {
      "air": "Trivandrum International Airport (TRV) - 52 km",
      "rail": "Nagercoil Junction - 16 km; Thiruvananthapuram Central - 55 km",
      "road": "Connected via NH 66 connecting Trivandrum and Kanyakumari",
      "local": "State buses, tourist taxis, walking tour inside palace"
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=800&auto=format&fit=crop&q=80"
    ],
    "model_3d": {"available": False, "type": "photogrammetry-in-progress"},
    "has_360": True,
    "has_video": True,
    "source": "Government of Kerala Archaeology Department",
    "last_updated": "2026-03-01"
  },
  {
    "id": "basilica-of-bom-jesus",
    "name": "Basilica of Bom Jesus & Old Goa Churches",
    "city": "Old Goa (Velha Goa)",
    "state": "Goa",
    "region": "Western India",
    "coordinates": {"lat": 15.5008, "lng": 73.9116},
    "era": "1594 - 1605 CE",
    "historical_period": "Portuguese Colonial Era in India",
    "architectural_style": "Baroque and Mannerist Jesuit Architecture",
    "architect": "Jesuit Master Builders & Goan Artisans",
    "material": "Exposed Basalt and Laterite stone with Gilded Altarpiece",
    "unesco_site": True,
    "historical_significance": "Houses the sacred mortal remains of St. Francis Xavier in a silver casket inside an Italian marble mausoleum crafted by Giovanni Battista Foggini.",
    "cultural_significance": "Part of the UNESCO 'Churches and Convents of Goa' inscription, landmark of Christian evangelization in Asia and Goan Catholic heritage.",
    "visiting_hours": "09:00 AM - 06:30 PM (Sundays: 10:30 AM - 06:30 PM)",
    "entry_fee_inr": 0,
    "entry_fee": {"domestic": 0, "international": 0, "currency": "₹"},
    "recommended_visit_duration": "2 Hours",
    "best_season": "November to February (Feast of St. Francis Xavier on Dec 3)",
    "nearby_destinations": ["Se Cathedral", "Church of St. Francis of Assisi", "Fontainhas Panaji"],
    "transport_information": {
      "air": "Dabolim Airport (GOI) - 25 km; Manohar International Airport Mopa (GOX) - 38 km",
      "rail": "Karmali Railway Station (KRMI) - 3 km (closest station)",
      "road": "Connected via Panaji-Old Goa highway along the Mandovi River (15 min drive)",
      "local": "Goa Kadamba electric buses, tourist taxis, rented scooters"
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&auto=format&fit=crop&q=80"
    ],
    "model_3d": {"available": False, "type": "photogrammetry-in-progress"},
    "has_360": True,
    "has_video": True,
    "source": "Archaeological Survey of India & UNESCO",
    "last_updated": "2026-03-01"
  },
  {
    "id": "fort-aguada",
    "name": "Fort Aguada & Lighthouse",
    "city": "Sinquerim / Candolim",
    "state": "Goa",
    "region": "Western India",
    "coordinates": {"lat": 15.4925, "lng": 73.7735},
    "era": "1612 CE",
    "historical_period": "Portuguese Administration (Governor Rui Tavares)",
    "architectural_style": "17th Century Portuguese Sea Fort & Bastion",
    "architect": "Portuguese Military Engineers",
    "material": "Red Laterite Stone Masonry",
    "unesco_site": False,
    "historical_significance": "A formidable fortress guarding the mouth of the Mandovi River against Dutch and Maratha fleets. 'Aguada' means water, as ships replenished freshwater from its 2.3-million-gallon cistern.",
    "cultural_significance": "Features Asia's first four-story lighthouse erected in 1864 and now houses the restored Aguada Port & Jail Heritage Museum.",
    "visiting_hours": "09:30 AM - 06:00 PM (Daily)",
    "entry_fee_inr": 25,
    "entry_fee": {"domestic": 25, "international": 200, "currency": "₹"},
    "recommended_visit_duration": "2 Hours",
    "best_season": "October to March",
    "nearby_destinations": ["Sinquerim Beach", "Candolim Beach", "Reis Magos Fort", "Panaji"],
    "transport_information": {
      "air": "Dabolim Airport (GOI) - 38 km; Mopa Airport (GOX) - 35 km",
      "rail": "Thivim Station - 22 km; Karmali - 25 km",
      "road": "Connected via coastal road through Candolim and Sinquerim",
      "local": "Rental scooters, app taxis (GoaMiles), local private cabs"
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?w=800&auto=format&fit=crop&q=80"
    ],
    "model_3d": {"available": False, "type": "photogrammetry-in-progress"},
    "has_360": True,
    "has_video": True,
    "source": "Archaeological Survey of India & Goa Heritage Action Group",
    "last_updated": "2026-03-01"
  },
  {
    "id": "golconda-fort",
    "name": "Golconda Fort & Qutb Shahi Citadel",
    "city": "Hyderabad",
    "state": "Telangana",
    "region": "Southern India",
    "coordinates": {"lat": 17.3833, "lng": 78.4011},
    "era": "1518 - 1591 CE",
    "historical_period": "Kakatiya Origins, expanded by Qutb Shahi Dynasty",
    "architectural_style": "Deccani Military Fortification Architecture",
    "architect": "Qutb Shahi Kings & Military Engineers",
    "material": "Granite blocks and Deccan hill bedrock",
    "unesco_site": False,
    "historical_significance": "Legendary capital and vault of the Golconda diamond trade that produced the Koh-i-Noor, Hope, and Daria-i-Noor diamonds. Famous for acoustic engineering where a clap at the Fateh Darwaza echoes at the Bala Hissar peak 1 km away.",
    "cultural_significance": "A testament to medieval water-raising systems, secret escape tunnels, and Deccani sultanate splendor.",
    "visiting_hours": "09:00 AM - 05:30 PM (Sound & Light Show: 06:30 PM & 07:45 PM)",
    "entry_fee_inr": 25,
    "entry_fee": {"domestic": 25, "international": 300, "currency": "₹"},
    "recommended_visit_duration": "3 Hours",
    "best_season": "October to March",
    "nearby_destinations": ["Qutb Shahi Tombs", "Charminar", "Chowmahalla Palace", "Salar Jung Museum"],
    "transport_information": {
      "air": "Rajiv Gandhi International Airport Hyderabad (HYD) - 28 km",
      "rail": "Hyderabad Deccan (Nampally) - 9 km; Secunderabad Junction - 16 km",
      "road": "Connected via Mehdipatnam corridor and Outer Ring Road",
      "local": "TSRTC city buses, Hyderabad Metro to Jubilee Hills + auto, app cabs"
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800&auto=format&fit=crop&q=80"
    ],
    "model_3d": {"available": False, "type": "photogrammetry-in-progress"},
    "has_360": True,
    "has_video": True,
    "source": "Archaeological Survey of India",
    "last_updated": "2026-03-01"
  },
  {
    "id": "charminar",
    "name": "Charminar Monument & Mosque",
    "city": "Hyderabad",
    "state": "Telangana",
    "region": "Southern India",
    "coordinates": {"lat": 17.3616, "lng": 78.4747},
    "era": "1591 CE",
    "historical_period": "Qutb Shahi Dynasty (Muhammad Quli Qutb Shah)",
    "architectural_style": "Indo-Islamic with Deccani architectural flourishes",
    "architect": "Mir Momin Astarabadi",
    "material": "Granite, limestone, mortar, and pulverized marble",
    "unesco_site": False,
    "historical_significance": "Built by Muhammad Quli Qutb Shah to commemorate the eradication of plague and foundation of Hyderabad city. Features four 56-meter-high grand minarets with double balconies.",
    "cultural_significance": "The global emblem of Hyderabad surrounded by the historic Laad Bazaar famous for lacquer bangles and Hyderabadi pearls.",
    "visiting_hours": "09:30 AM - 05:30 PM (Daily)",
    "entry_fee_inr": 25,
    "entry_fee": {"domestic": 25, "international": 300, "currency": "₹"},
    "recommended_visit_duration": "1.5 Hours",
    "best_season": "October to March",
    "nearby_destinations": ["Mecca Masjid", "Chowmahalla Palace", "Laad Bazaar", "Golconda Fort"],
    "transport_information": {
      "air": "Hyderabad Airport (HYD) - 20 km",
      "rail": "Hyderabad Deccan Station - 4 km; Kacheguda - 5 km",
      "road": "Old City core along the Musi River",
      "local": "Hyderabad Metro Green Line (MGBS Station - 1.8 km), auto-rickshaws"
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1588097281266-31018512954b?w=800&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1588097281266-31018512954b?w=800&auto=format&fit=crop&q=80"
    ],
    "model_3d": {"available": False, "type": "photogrammetry-in-progress"},
    "has_360": True,
    "has_video": True,
    "source": "Archaeological Survey of India",
    "last_updated": "2026-03-01"
  },
  {
    "id": "victoria-memorial-kolkata",
    "name": "Victoria Memorial Hall",
    "city": "Kolkata",
    "state": "West Bengal",
    "region": "Eastern India",
    "coordinates": {"lat": 22.5448, "lng": 88.3426},
    "era": "1906 - 1921 CE",
    "historical_period": "British Colonial India (Lord Curzon initiative)",
    "architectural_style": "Indo-Saracenic Revival fused with British and Mughal styles",
    "architect": "Sir William Emerson and Vincent Esch",
    "material": "Makrana white marble and bronze Angel of Victory finial",
    "unesco_site": False,
    "historical_significance": "Grand marble monument dedicated to Queen Victoria, surrounded by 64 acres of landscaped gardens, housing 25 galleries of rare historical paintings, weapons, and manuscripts.",
    "cultural_significance": "The quintessential symbol of Kolkata's colonial artistic legacy and intellectual heritage.",
    "visiting_hours": "Gallery: 10:00 AM - 05:00 PM (Closed Mondays); Gardens: 05:30 AM - 06:00 PM",
    "entry_fee_inr": 50,
    "entry_fee": {"domestic": 50, "international": 500, "currency": "₹"},
    "recommended_visit_duration": "2.5 Hours",
    "best_season": "October to March",
    "nearby_destinations": ["St. Paul's Cathedral", "Indian Museum", "Howrah Bridge", "Dakshineswar Kali Temple"],
    "transport_information": {
      "air": "Netaji Subhash Chandra Bose Airport (CCU) - 20 km",
      "rail": "Howrah Junction - 6 km; Sealdah - 5 km",
      "road": "Queens Way and Jawaharlal Nehru Road corridor in Maidan precinct",
      "local": "Kolkata Metro Blue Line (Rabindra Sadan or Maidan station - 800 m), yellow taxis"
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1558431382-27e303142255?w=800&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1558431382-27e303142255?w=800&auto=format&fit=crop&q=80"
    ],
    "model_3d": {"available": False, "type": "photogrammetry-in-progress"},
    "has_360": True,
    "has_video": True,
    "source": "Victoria Memorial Trust & Ministry of Culture",
    "last_updated": "2026-03-01"
  },
  {
    "id": "nalanda-university-ruins",
    "name": "Nalanda Mahavihara Ancient University Ruins",
    "city": "Nalanda (Rajgir)",
    "state": "Bihar",
    "region": "Eastern India",
    "coordinates": {"lat": 25.1357, "lng": 85.4449},
    "era": "5th - 12th Century CE",
    "historical_period": "Gupta Empire to Pala Dynasty",
    "architectural_style": "Ancient Monastic Mahavihara Brick Architecture",
    "architect": "Gupta Emperors (Kumaragupta I) and Buddhist scholars",
    "material": "Burnt clay bricks with lime mortar and stucco reliefs",
    "unesco_site": True,
    "historical_significance": "The world's earliest residential international university, housing 10,000 students and 2,000 teachers from across China, Korea, Tibet, and Central Asia until its sack in 1193 CE.",
    "cultural_significance": "A beacon of human intellectual pursuit where logic, astronomy, medicine, philosophy, and linguistics were debated.",
    "visiting_hours": "09:00 AM - 05:00 PM (Daily)",
    "entry_fee_inr": 40,
    "entry_fee": {"domestic": 40, "international": 600, "currency": "₹"},
    "recommended_visit_duration": "3 Hours",
    "best_season": "October to March",
    "nearby_destinations": ["Nalanda Archaeological Museum", "Hiuen Tsang Memorial", "Rajgir Ropeway & Vulture Peak"],
    "transport_information": {
      "air": "Patna Airport (PAT) - 85 km; Gaya Airport - 95 km",
      "rail": "Rajgir Railway Station - 12 km; Bakhtiyarpur Junction - 45 km",
      "road": "Connected via state highway SH 78 from Patna and Rajgir",
      "local": "E-rickshaws, tongas, guided walking tours along preserved brick cloisters"
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800&auto=format&fit=crop&q=80"
    ],
    "model_3d": {"available": False, "type": "photogrammetry-in-progress"},
    "has_360": True,
    "has_video": True,
    "source": "Archaeological Survey of India & UNESCO",
    "last_updated": "2026-03-01"
  },
  {
    "id": "rani-ki-vav",
    "name": "Rani ki Vav (The Queen's Stepwell)",
    "city": "Patan",
    "state": "Gujarat",
    "region": "Western India",
    "coordinates": {"lat": 23.8589, "lng": 72.1017},
    "era": "1063 CE",
    "historical_period": "Chaulukya / Solanki Dynasty (Queen Udayamati)",
    "architectural_style": "Maru-Gurjara Inverted Temple Stepwell Architecture",
    "architect": "Commissioned by Queen Udayamati in memory of King Bhima I",
    "material": "Carved Sandstone tiered across seven levels",
    "unesco_site": True,
    "historical_significance": "Designed as an inverted subterranean temple sanctifying water, descending seven terraces decorated with over 500 principal sculptures and 1,000 minor religious figurines.",
    "cultural_significance": "Depicted on the reverse of the modern Indian ₹100 banknote, honoring water conservation as a sacred communal rite.",
    "visiting_hours": "08:00 AM - 06:00 PM (Daily)",
    "entry_fee_inr": 40,
    "entry_fee": {"domestic": 40, "international": 600, "currency": "₹"},
    "recommended_visit_duration": "2 Hours",
    "best_season": "October to March",
    "nearby_destinations": ["Modhera Sun Temple", "Patan Patola Saree Weaving Center", "Sahastralinga Talav"],
    "transport_information": {
      "air": "Sardar Vallabhbhai Patel International Airport Ahmedabad (AMD) - 125 km",
      "rail": "Mehsana Junction - 50 km; Patan Station - 4 km",
      "road": "Connected via state expressway from Ahmedabad (2.5 hrs drive)",
      "local": "Local auto-rickshaws, paved descent walkways with wheelchair ramps to upper tier"
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1600100397608-f010e422a59e?w=800&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1600100397608-f010e422a59e?w=800&auto=format&fit=crop&q=80"
    ],
    "model_3d": {"available": False, "type": "photogrammetry-in-progress"},
    "has_360": True,
    "has_video": True,
    "source": "Archaeological Survey of India & UNESCO",
    "last_updated": "2026-03-01"
  },
  {
    "id": "champaner-pavagadh",
    "name": "Champaner-Pavagadh Archaeological Park",
    "city": "Panchmahal",
    "state": "Gujarat",
    "region": "Western India",
    "coordinates": {"lat": 22.4833, "lng": 73.5333},
    "era": "8th - 16th Century CE",
    "historical_period": "Chavda, Chauhan, and Gujarat Sultanate (Mahmud Begada)",
    "architectural_style": "Synthesis of Hindu-Jain architecture and early Islamic Sultanate design",
    "architect": "Royal Guilds of Sultan Mahmud Begada",
    "material": "Local sandstone and hill basalt rock",
    "unesco_site": True,
    "historical_significance": "A complete un-excavated archaeological city containing 114 monuments, grand mosques (Jami Masjid), palaces, and the Kalika Mata hill temple.",
    "cultural_significance": "The only complete and unchanged Islamic pre-Mughal city in India.",
    "visiting_hours": "08:30 AM - 05:00 PM (Daily)",
    "entry_fee_inr": 40,
    "entry_fee": {"domestic": 40, "international": 600, "currency": "₹"},
    "recommended_visit_duration": "4 Hours",
    "best_season": "October to March",
    "nearby_destinations": ["Vadodara Laxmi Vilas Palace", "Statue of Unity (Kevadia - 80 km)"],
    "transport_information": {
      "air": "Vadodara Airport (BDQ) - 45 km; Ahmedabad Airport - 145 km",
      "rail": "Vadodara Junction - 48 km; Champaner Road Station - 18 km",
      "road": "Connected via 4-lane highway from Vadodara (50 mins drive)",
      "local": "Pavagadh ropeway to hilltop temple, state shuttle buses, private taxis"
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1600100397608-f010e422a59e?w=800&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1600100397608-f010e422a59e?w=800&auto=format&fit=crop&q=80"
    ],
    "model_3d": {"available": False, "type": "photogrammetry-in-progress"},
    "has_360": True,
    "has_video": True,
    "source": "Archaeological Survey of India & UNESCO",
    "last_updated": "2026-03-01"
  },
  {
    "id": "golden-temple-amritsar",
    "name": "Sri Harmandir Sahib (The Golden Temple)",
    "city": "Amritsar",
    "state": "Punjab",
    "region": "Northern India",
    "coordinates": {"lat": 31.6200, "lng": 74.8765},
    "era": "1581 - 1604 CE / 1830 Gold Cladding",
    "historical_period": "Guru Arjan Sahib (5th Sikh Guru) & Maharaja Ranjit Singh",
    "architectural_style": "Sikh Architecture (Synthesis of Rajput and Mughal forms)",
    "architect": "Designed by Guru Arjan Dev; marble and gold plating by Maharaja Ranjit Singh",
    "material": "White marble base with 500 kg of pure 24-karat gold leaf gilding",
    "unesco_site": False,
    "historical_significance": "The holiest Gurdwara of Sikhism built in the center of the Amrit Sarovar pool. Operates the world's largest free community kitchen (Guru ka Langar) feeding 100,000 people daily regardless of religion, caste, or background.",
    "cultural_significance": "Four open doorways symbolize unconditional welcoming of all humanity from all four corners of the Earth.",
    "visiting_hours": "Open 24 hours (Langar served continuously)",
    "entry_fee_inr": 0,
    "entry_fee": {"domestic": 0, "international": 0, "currency": "₹"},
    "recommended_visit_duration": "3 Hours",
    "best_season": "October to March",
    "nearby_destinations": ["Jallianwala Bagh", "Wagah Border Ceremony", "Partition Museum"],
    "transport_information": {
      "air": "Sri Guru Ram Dass Jee International Airport Amritsar (ATQ) - 13 km",
      "rail": "Amritsar Junction (ASR) - 2.5 km (frequent Shatabdi and Vande Bharat)",
      "road": "Grand Trunk Road (NH 44) direct corridor",
      "local": "Free SGPC pilgrim shuttle buses, e-rickshaws, Heritage Street pedestrian plaza"
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800&auto=format&fit=crop&q=80"
    ],
    "model_3d": {"available": False, "type": "photogrammetry-in-progress"},
    "has_360": True,
    "has_video": True,
    "source": "Shiromani Gurdwara Parbandhak Committee (SGPC)",
    "last_updated": "2026-03-01"
  },
  {
    "id": "mehrangarh-fort",
    "name": "Mehrangarh Fort (Citadel of the Sun)",
    "city": "Jodhpur",
    "state": "Rajasthan",
    "region": "Northern India",
    "coordinates": {"lat": 26.2978, "lng": 73.0185},
    "era": "1459 CE",
    "historical_period": "Rathore Rajput Dynasty (Rao Jodha)",
    "architectural_style": "Impregnable Rajput Citadel Architecture",
    "architect": "Rao Jodha and succeeding Rathore Maharajas",
    "material": "Red sandstone hewn directly from the perpendicular cliff",
    "unesco_site": False,
    "historical_significance": "Rising 410 feet above the Blue City of Jodhpur, with seven fortified gates (Jaipol, Fatehpol). Preserves cannonball scars from 18th-century battles with Jaipur armies.",
    "cultural_significance": "Rudyard Kipling termed it 'a palace that might have been built by Titans and colored by the morning sun.' Houses one of India's finest museum collections of royal palanquins and howdahs.",
    "visiting_hours": "09:00 AM - 05:00 PM (Daily)",
    "entry_fee_inr": 100,
    "entry_fee": {"domestic": 100, "international": 600, "currency": "₹"},
    "recommended_visit_duration": "3 Hours",
    "best_season": "October to March",
    "nearby_destinations": ["Jaswant Thada", "Umaid Bhawan Palace", "Clock Tower Market"],
    "transport_information": {
      "air": "Jodhpur Airport (JDH) - 8 km",
      "rail": "Jodhpur Railway Station (JU) - 5 km",
      "road": "Connected via state highways through western Rajasthan",
      "local": "Elevator access from fort base, auto-rickshaws, flying fox zipline"
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&auto=format&fit=crop&q=80"
    ],
    "model_3d": {"available": False, "type": "photogrammetry-in-progress"},
    "has_360": True,
    "has_video": True,
    "source": "Mehrangarh Museum Trust",
    "last_updated": "2026-03-01"
  },
  {
    "id": "jaisalmer-fort",
    "name": "Jaisalmer Fort (Sonar Qila / Golden Fort)",
    "city": "Jaisalmer",
    "state": "Rajasthan",
    "region": "Northern India",
    "coordinates": {"lat": 26.9124, "lng": 70.9127},
    "era": "1156 CE",
    "historical_period": "Bhati Rajput Dynasty (Rawal Jaisal)",
    "architectural_style": "Thar Desert Living Fort Architecture with 99 Bastions",
    "architect": "Rawal Jaisal & Royal Bhati Craftsmen",
    "material": "Yellow sandstone that turns lion-gold at sunset",
    "unesco_site": True,
    "historical_significance": "A UNESCO World Heritage hill fort and one of the world's very few surviving 'living forts' where a quarter of the city's population still resides inside ancient stone ramparts.",
    "cultural_significance": "Features seven medieval Jain temples with delicate stone tracery and ancient palm-leaf manuscripts.",
    "visiting_hours": "09:00 AM - 06:00 PM (Fort alleys open 24/7)",
    "entry_fee_inr": 50,
    "entry_fee": {"domestic": 50, "international": 250, "currency": "₹"},
    "recommended_visit_duration": "3 Hours",
    "best_season": "November to February",
    "nearby_destinations": ["Patwon ki Haveli", "Sam Sand Dunes", "Gadisar Lake", "Kuldhara Ghost Village"],
    "transport_information": {
      "air": "Jaisalmer Airport (JSA) - 15 km; Jodhpur - 280 km",
      "rail": "Jaisalmer Railway Station - 2 km (Palace on Wheels stop)",
      "road": "Connected via NH 11 highway across Thar desert",
      "local": "Pedestrian exploration inside stone alleys, auto-rickshaws outside"
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&auto=format&fit=crop&q=80"
    ],
    "model_3d": {"available": False, "type": "photogrammetry-in-progress"},
    "has_360": True,
    "has_video": True,
    "source": "Archaeological Survey of India & UNESCO",
    "last_updated": "2026-03-01"
  },
  {
    "id": "chittorgarh-fort",
    "name": "Chittorgarh Fort (Pride of Rajputana)",
    "city": "Chittorgarh",
    "state": "Rajasthan",
    "region": "Northern India",
    "coordinates": {"lat": 24.8879, "lng": 74.6453},
    "era": "7th Century CE",
    "historical_period": "Mori / Sisodia Rajput Dynasties",
    "architectural_style": "Hill Fortress with Vijay Stambha (Tower of Victory)",
    "architect": "Chitrangada Mori & Maharana Kumbha",
    "material": "Granite bedrock and sandstone masonry",
    "unesco_site": True,
    "historical_significance": "Largest fort in India, spanning 700 acres over a 180-meter hill. The immortal stage of historic sieges by Alauddin Khalji and Akbar, remembered for the legendary bravery of Maharana Pratap and Rani Padmini.",
    "cultural_significance": "The nine-story Vijay Stambha and Kirti Stambha stand as supreme monuments to Rajput valor.",
    "visiting_hours": "09:00 AM - 06:00 PM (Daily)",
    "entry_fee_inr": 40,
    "entry_fee": {"domestic": 40, "international": 600, "currency": "₹"},
    "recommended_visit_duration": "4 Hours",
    "best_season": "October to March",
    "nearby_destinations": ["Padmini Palace", "Vijay Stambha", "Kalika Mata Temple", "Udaipur"],
    "transport_information": {
      "air": "Maharana Pratap Airport Udaipur (UDR) - 90 km",
      "rail": "Chittorgarh Junction (COR) - 6 km",
      "road": "Connected via Golden Quadrilateral highway network",
      "local": "Private tourist vehicles or auto-rickshaws required due to 700-acre scale"
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&auto=format&fit=crop&q=80"
    ],
    "model_3d": {"available": False, "type": "photogrammetry-in-progress"},
    "has_360": True,
    "has_video": True,
    "source": "Archaeological Survey of India & UNESCO",
    "last_updated": "2026-03-01"
  },
  {
    "id": "cellular-jail-port-blair",
    "name": "Cellular Jail National Memorial (Kala Pani)",
    "city": "Port Blair",
    "state": "Andaman and Nicobar Islands",
    "region": "Island Territory",
    "coordinates": {"lat": 11.6738, "lng": 92.7480},
    "era": "1896 - 1906 CE",
    "historical_period": "British Colonial Era (Penal Settlement)",
    "architectural_style": "Panopticon Radial Seven-Winged Prison Design",
    "architect": "British Colonial Engineers",
    "material": "Porous bricks transported from Burma",
    "unesco_site": False,
    "historical_significance": "Colonial prison built to exile political dissidents of the Indian Independence Movement, including Veer Savarkar and Batukeshwar Dutt. Three of the original seven wings survive.",
    "cultural_significance": "A revered pilgrimage of Indian freedom struggle and national sacrifice.",
    "visiting_hours": "09:00 AM - 12:30 PM & 01:30 PM - 04:45 PM (Light & Sound: 06:00 PM; Closed Mondays)",
    "entry_fee_inr": 30,
    "entry_fee": {"domestic": 30, "international": 100, "currency": "₹"},
    "recommended_visit_duration": "2.5 Hours",
    "best_season": "October to May",
    "nearby_destinations": ["Ross Island (Netaji Subhash Chandra Bose Dweep)", "Corbyn's Cove Beach", "Havelock Island (Swaraj Dweep)"],
    "transport_information": {
      "air": "Veer Savarkar International Airport Port Blair (IXZ) - 4 km",
      "rail": "Island territory - No railway network (connected by air and passenger ships from Chennai/Kolkata)",
      "road": "Connected to Port Blair city center via Marina Park road",
      "local": "Local auto-rickshaws, tourist cabs, city buses"
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?w=800&auto=format&fit=crop&q=80"
    ],
    "model_3d": {"available": False, "type": "photogrammetry-in-progress"},
    "has_360": True,
    "has_video": True,
    "source": "Andaman & Nicobar Administration & Ministry of Culture",
    "last_updated": "2026-03-01"
  },
  {
    "id": "kanheri-caves",
    "name": "Kanheri Caves (Krishnagiri)",
    "city": "Mumbai (Sanjay Gandhi National Park)",
    "state": "Maharashtra",
    "region": "Western India",
    "coordinates": {"lat": 19.2057, "lng": 72.9067},
    "era": "1st Century BCE - 10th Century CE",
    "historical_period": "Maurya, Satavahana, and Silahara Dynasties",
    "architectural_style": "Rock-cut Buddhist Viharas and Chaityas with Ancient Rainwater Channels",
    "architect": "Buddhist Monks & Guild Craftsmen",
    "material": "Monolithic Basalt hill excavation",
    "unesco_site": False,
    "historical_significance": "A massive complex of 109 rock-cut Buddhist caves nestled deep in Sanjay Gandhi National Park, featuring massive 7-meter standing Buddha statues and a Sophisticated 2,000-year-old rainwater harvesting cistern system.",
    "cultural_significance": "One of the greatest Buddhist monastic universities in Western India, serving ancient trade routes connecting Sopara and Kalyan ports.",
    "visiting_hours": "09:00 AM - 05:00 PM (Park closes entry at 05:30 PM)",
    "entry_fee_inr": 25,
    "entry_fee": {"domestic": 25, "international": 300, "currency": "₹"},
    "recommended_visit_duration": "3 Hours",
    "best_season": "July to February (stunning during monsoons)",
    "nearby_destinations": ["Sanjay Gandhi National Park", "Global Vipassana Pagoda", "Elephanta Caves"],
    "transport_information": {
      "air": "Mumbai Airport (BOM) - 20 km",
      "rail": "Borivali Railway Station (Western Line) - 7 km",
      "road": "Western Express Highway to SGNP main gate at Borivali East",
      "local": "Park electric shuttle bus from SGNP gate to caves (6 km), rental bicycles"
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=800&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=800&auto=format&fit=crop&q=80"
    ],
    "model_3d": {"available": False, "type": "photogrammetry-in-progress"},
    "has_360": True,
    "has_video": True,
    "source": "Archaeological Survey of India & Maharashtra Forest Dept",
    "last_updated": "2026-03-01"
  },
  {
    "id": "jantar-mantar-delhi",
    "name": "Jantar Mantar Delhi",
    "city": "New Delhi",
    "state": "Delhi (NCT)",
    "region": "Northern India",
    "coordinates": {"lat": 28.6271, "lng": 77.2166},
    "era": "1724 CE",
    "historical_period": "Mughal Era (Maharaja Sawai Jai Singh II of Jaipur)",
    "architectural_style": "Monumental Geometric Astronomical Masonry",
    "architect": "Maharaja Sawai Jai Singh II",
    "material": "Brick rubble dressed with lime plaster and red ocher",
    "unesco_site": False,
    "historical_significance": "The first of five astronomical observatories built by Jai Singh II, featuring 13 architectural astronomy instruments including the Samrat Yantra, Jayaprakash, and Misra Yantra.",
    "cultural_significance": "A pioneering scientific heritage site in the heart of modern New Delhi.",
    "visiting_hours": "06:00 AM - 06:00 PM (Daily)",
    "entry_fee_inr": 25,
    "entry_fee": {"domestic": 25, "international": 300, "currency": "₹"},
    "recommended_visit_duration": "1.5 Hours",
    "best_season": "October to March",
    "nearby_destinations": ["Connaught Place", "Bangla Sahib Gurdwara", "Agrasen ki Baoli"],
    "transport_information": {
      "air": "Indira Gandhi Airport (DEL) - 14 km",
      "rail": "New Delhi Station - 2 km",
      "road": "Sansad Marg corridor near Connaught Place",
      "local": "Delhi Metro (Patel Chowk / Rajiv Chowk stations - 400 m)"
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1548013146-72479768bada?w=800&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1548013146-72479768bada?w=800&auto=format&fit=crop&q=80"
    ],
    "model_3d": {"available": False, "type": "photogrammetry-in-progress"},
    "has_360": True,
    "has_video": True,
    "source": "Archaeological Survey of India",
    "last_updated": "2026-03-01"
  },
  {
    "id": "agrasen-ki-baoli",
    "name": "Agrasen ki Baoli (Ancient Stepwell)",
    "city": "New Delhi",
    "state": "Delhi (NCT)",
    "region": "Northern India",
    "coordinates": {"lat": 28.6258, "lng": 77.2250},
    "era": "14th Century CE (Rebuilt)",
    "historical_period": "Originally attributed to King Agrasen, reconstructed during Tughlaq/Lodi period",
    "architectural_style": "Deep Stepwell (Baoli) with Multi-tier Arched Niches",
    "architect": "Unknown Medieval Craftsmen",
    "material": "Red sandstone and rubble masonry",
    "unesco_site": False,
    "historical_significance": "A 60-meter-long by 15-meter-wide stepwell consisting of 108 stone steps, one of Delhi's best-preserved subterranean water structures.",
    "cultural_significance": "A serene architectural retreat hidden among Connaught Place's modern skyscrapers.",
    "visiting_hours": "09:00 AM - 05:30 PM (Daily)",
    "entry_fee_inr": 0,
    "entry_fee": {"domestic": 0, "international": 0, "currency": "₹"},
    "recommended_visit_duration": "1 Hour",
    "best_season": "October to March",
    "nearby_destinations": ["Jantar Mantar", "India Gate", "National Museum"],
    "transport_information": {
      "air": "Delhi Airport (DEL) - 14 km",
      "rail": "New Delhi Station - 2.5 km",
      "road": "Hailey Road off Kasturba Gandhi Marg",
      "local": "Delhi Metro (Barakhamba Road station - 500 m)"
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&auto=format&fit=crop&q=80"
    ],
    "model_3d": {"available": False, "type": "photogrammetry-in-progress"},
    "has_360": True,
    "has_video": True,
    "source": "Archaeological Survey of India",
    "last_updated": "2026-03-01"
  },
  {
    "id": "lodhi-gardens",
    "name": "Lodhi Gardens & Royal Tombs",
    "city": "New Delhi",
    "state": "Delhi (NCT)",
    "region": "Northern India",
    "coordinates": {"lat": 28.5931, "lng": 77.2197},
    "era": "1444 - 1517 CE",
    "historical_period": "Sayyid and Lodi Dynasties (Mohammed Shah & Sikandar Lodi)",
    "architectural_style": "Octagonal and Square Pashtun Tomb Architecture",
    "architect": "Lodi Dynasty Royal Architects",
    "material": "Local quartzite rubble dressed with sandstone and blue glazed tiles",
    "unesco_site": False,
    "historical_significance": "Sprawling 90-acre heritage park containing the Tomb of Sikandar Lodi, Shisha Gumbad, Bara Gumbad, and the Athpula (eight-piered bridge built during Akbar's reign).",
    "cultural_significance": "Beloved public botanical lung where morning walkers and heritage enthusiasts interact with living history.",
    "visiting_hours": "06:00 AM - 08:00 PM (Daily)",
    "entry_fee_inr": 0,
    "entry_fee": {"domestic": 0, "international": 0, "currency": "₹"},
    "recommended_visit_duration": "2 Hours",
    "best_season": "October to March",
    "nearby_destinations": ["Humayun's Tomb", "Safdarjung Tomb", "Khan Market"],
    "transport_information": {
      "air": "Delhi Airport (DEL) - 13 km",
      "rail": "Hazrat Nizamuddin - 4 km",
      "road": "Lodhi Road and Max Mueller Marg",
      "local": "Delhi Metro (Jor Bagh or JLN Stadium stations - 800 m)"
    },
    "thumbnail_url": "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&auto=format&fit=crop&q=80",
    "images": [
      "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&auto=format&fit=crop&q=80"
    ],
    "model_3d": {"available": False, "type": "photogrammetry-in-progress"},
    "has_360": True,
    "has_video": True,
    "source": "Archaeological Survey of India & NDMC",
    "last_updated": "2026-03-01"
  }
]

print(f"Total structured heritage experiences generated: {len(heritage_42)}")

with open('data/heritage/monuments.json', 'w', encoding='utf-8') as f:
    json.dump(heritage_42, f, indent=2, ensure_ascii=False)

print("Successfully wrote 42 Heritage Experiences to data/heritage/monuments.json")
